import { BaseTool } from "../../../libs/ui-engine-v0_2_0/index.js";

export class ApplicantRequestTool extends BaseTool {

    override render($root: UiEngineRoot): void {
        super.render($root);

        const html = /*html*/ `
            <section
                class="applicant-request"
                aria-labelledby="applicant-request-title"
            >
                <header class="applicant-request__header">
                    <h1
                        id="applicant-request-title"
                        class="applicant-request__title"
                    >
                        Applicant / Request
                    </h1>

                    <p class="applicant-request__description">
                        Complete the required data before evaluation.
                    </p>
                </header>

                <form
                    id="applicant-request-form"
                    class="applicant-request__form"
                    autocomplete="off"
                >
                    <!-- Application metadata -->
                    <section class="applicant-request__section">
                        <h2 class="applicant-request__section-title">
                            Application
                        </h2>

                        <div class="applicant-request__fields">
                            <!-- Application number -->
                            <div class="applicant-request__field">
                                <label for="application-number">
                                    Application number
                                </label>

                                <div class="applicant-request__input-wrapper">
                                    <input
                                        id="application-number"
                                        type="text"
                                        value="Assigned by server"
                                        aria-describedby="application-number-hint"
                                        readonly
                                    >
                                </div>

                                <small
                                    id="application-number-hint"
                                    class="applicant-request__hint"
                                >
                                    Generated by the server after submission.
                                </small>
                            </div>

                            <!-- Scoring model -->
                            <div class="applicant-request__field">
                                <label for="scoring-model">
                                    Scoring model
                                </label>

                                <div class="applicant-request__input-wrapper">
                                    <select
                                        id="scoring-model"
                                        name="scoring_model"
                                        aria-describedby="scoring-model-hint"
                                        required
                                    >
                                        <option value="0.1.0">
                                            Scoring Model 0.1.0
                                        </option>
                                        <option value="0.2.0" selected>
                                            Scoring Model 0.2.0
                                        </option>
                                    </select>
                                </div>

                                <small
                                    id="scoring-model-hint"
                                    class="applicant-request__hint"
                                >
                                    Defines the rule set used for this assessment.
                                </small>
                            </div>
                        </div>
                    </section>

                    <!-- Applicant information -->
                    <section class="applicant-request__section">
                        <h2 class="applicant-request__section-title">
                            Applicant
                        </h2>

                        <div class="applicant-request__fields">
                            <!-- Age -->
                            <div class="applicant-request__field">
                                <label for="age">
                                    Age
                                </label>

                                <div class="applicant-request__input-wrapper">
                                    <input
                                        id="age"
                                        name="age"
                                        type="number"
                                        min="18"
                                        max="120"
                                        step="1"
                                        placeholder="35"
                                        aria-describedby="age-hint"
                                        required
                                    >

                                    <span class="applicant-request__input-unit">
                                        years
                                    </span>
                                </div>

                                <small
                                    id="age-hint"
                                    class="applicant-request__hint"
                                >
                                    Applicant's age in completed years.
                                </small>
                            </div>

                            <!-- Employment duration -->
                            <div class="applicant-request__field">
                                <label for="employment-months">
                                    Employment duration
                                </label>

                                <div class="applicant-request__input-wrapper">
                                    <input
                                        id="employment-months"
                                        name="employment_months"
                                        type="number"
                                        min="0"
                                        step="1"
                                        placeholder="48"
                                        aria-describedby="employment-months-hint"
                                        required
                                    >

                                    <span class="applicant-request__input-unit">
                                        months
                                    </span>
                                </div>

                                <small
                                    id="employment-months-hint"
                                    class="applicant-request__hint"
                                >
                                    Continuous employment with the current employer.
                                </small>
                            </div>
                        </div>
                    </section>

                    <!-- Financial information -->
                    <section class="applicant-request__section">
                        <h2 class="applicant-request__section-title">
                            Financial situation
                        </h2>

                        <div class="applicant-request__fields">
                            <!-- Monthly net income -->
                            <div class="applicant-request__field">
                                <label for="monthly-net-income">
                                    Monthly net income
                                </label>

                                <div class="applicant-request__input-wrapper">
                                    <input
                                        id="monthly-net-income"
                                        name="monthly_net_income"
                                        type="number"
                                        min="0"
                                        step="0.01"
                                        placeholder="3800.00"
                                        aria-describedby="monthly-net-income-hint"
                                        required
                                    >

                                    <span class="applicant-request__input-unit">
                                        EUR
                                    </span>
                                </div>

                                <small
                                    id="monthly-net-income-hint"
                                    class="applicant-request__hint"
                                >
                                    Applicant's regular monthly income after taxes.
                                </small>
                            </div>

                            <!-- Monthly fixed costs -->
                            <div class="applicant-request__field">
                                <label for="monthly-fixed-costs">
                                    Monthly fixed costs
                                </label>

                                <div class="applicant-request__input-wrapper">
                                    <input
                                        id="monthly-fixed-costs"
                                        name="monthly_fixed_costs"
                                        type="number"
                                        min="0"
                                        step="0.01"
                                        placeholder="1350.00"
                                        aria-describedby="monthly-fixed-costs-hint"
                                        required
                                    >

                                    <span class="applicant-request__input-unit">
                                        EUR
                                    </span>
                                </div>

                                <small
                                    id="monthly-fixed-costs-hint"
                                    class="applicant-request__hint"
                                >
                                    Recurring living costs excluding debt payments.
                                </small>
                            </div>

                            <!-- Existing monthly debt payments -->
                            <div class="applicant-request__field">
                                <label for="existing-debt-payments">
                                    Existing debt payments
                                </label>

                                <div class="applicant-request__input-wrapper">
                                    <input
                                        id="existing-debt-payments"
                                        name="existing_monthly_debt_payments"
                                        type="number"
                                        min="0"
                                        step="0.01"
                                        placeholder="180.00"
                                        aria-describedby="existing-debt-payments-hint"
                                        required
                                    >

                                    <span class="applicant-request__input-unit">
                                        EUR
                                    </span>
                                </div>

                                <small
                                    id="existing-debt-payments-hint"
                                    class="applicant-request__hint"
                                >
                                    Total monthly payments for existing credit obligations.
                                </small>
                            </div>

                            <!-- Cash reserve -->
                            <div class="applicant-request__field">
                                <label for="cash-reserve">
                                    Cash reserve
                                </label>

                                <div class="applicant-request__input-wrapper">
                                    <input
                                        id="cash-reserve"
                                        name="cash_reserve"
                                        type="number"
                                        min="0"
                                        step="0.01"
                                        placeholder="18000.00"
                                        aria-describedby="cash-reserve-hint"
                                        required
                                    >

                                    <span class="applicant-request__input-unit">
                                        EUR
                                    </span>
                                </div>

                                <small
                                    id="cash-reserve-hint"
                                    class="applicant-request__hint"
                                >
                                    Immediately available liquid savings.
                                </small>
                            </div>
                        </div>
                    </section>

                    <!-- Requested loan -->
                    <section class="applicant-request__section">
                        <h2 class="applicant-request__section-title">
                            Loan request
                        </h2>

                        <div class="applicant-request__fields">
                            <!-- Loan amount -->
                            <div class="applicant-request__field">
                                <label for="loan-amount">
                                    Loan amount
                                </label>

                                <div class="applicant-request__input-wrapper">
                                    <input
                                        id="loan-amount"
                                        name="loan_amount"
                                        type="number"
                                        min="0.01"
                                        step="0.01"
                                        placeholder="12000.00"
                                        aria-describedby="loan-amount-hint"
                                        required
                                    >

                                    <span class="applicant-request__input-unit">
                                        EUR
                                    </span>
                                </div>

                                <small
                                    id="loan-amount-hint"
                                    class="applicant-request__hint"
                                >
                                    Principal amount requested by the applicant.
                                </small>
                            </div>

                            <!-- Annual interest rate -->
                            <div class="applicant-request__field">
                                <label for="annual-interest-rate">
                                    Annual interest rate
                                </label>

                                <div class="applicant-request__input-wrapper">
                                    <input
                                        id="annual-interest-rate"
                                        name="annual_interest_rate"
                                        type="number"
                                        min="0"
                                        max="100"
                                        step="0.01"
                                        placeholder="5.20"
                                        aria-describedby="annual-interest-rate-hint"
                                        required
                                    >

                                    <span class="applicant-request__input-unit">
                                        %
                                    </span>
                                </div>

                                <small
                                    id="annual-interest-rate-hint"
                                    class="applicant-request__hint"
                                >
                                    Nominal annual interest rate in percent.
                                </small>
                            </div>

                            <!-- Loan term -->
                            <div class="applicant-request__field">
                                <label for="loan-term-months">
                                    Loan term
                                </label>

                                <div class="applicant-request__input-wrapper">
                                    <input
                                        id="loan-term-months"
                                        name="loan_term_months"
                                        type="number"
                                        min="1"
                                        step="1"
                                        placeholder="36"
                                        aria-describedby="loan-term-months-hint"
                                        required
                                    >

                                    <span class="applicant-request__input-unit">
                                        months
                                    </span>
                                </div>

                                <small
                                    id="loan-term-months-hint"
                                    class="applicant-request__hint"
                                >
                                    Requested repayment period in full months.
                                </small>
                            </div>
                        </div>
                    </section>

                    <footer class="applicant-request__actions">
                        <button
                            class="applicant-request__submit"
                            type="submit"
                        >
                            Evaluate application
                        </button>
                    </footer>
                </form>
            </section>
        `;

        $root.html(html);
    }
}